import { createCipheriv, createDecipheriv, randomBytes } from "node:crypto"
import { log } from "../utils/log"

// Encryption at rest for notification connector secrets (webhook URLs and
// headers, SMTP passwords). The key is HSI_SECRETS_KEY in the backend .env,
// generated by install.sh and independent of JWT_SECRET, so rotating the JWT
// secret never makes stored secrets unreadable.

export const UNREADABLE_SECRETS = "secrets unreadable, re-enter them in Settings > Notifications"
const PREFIX = "enc:v1:"

export class SecretsError extends Error {
  constructor(message: string) {
    super(message)
    this.name = "SecretsError"
  }
}

let warnedInvalid = false

/** Reads HSI_SECRETS_KEY (64 hex chars) at call time; null when unset or invalid. */
export function secretsKey(): Buffer | null {
  const raw = process.env.HSI_SECRETS_KEY?.trim()
  if (!raw) return null
  if (!/^[0-9a-fA-F]{64}$/.test(raw)) {
    if (!warnedInvalid) {
      warnedInvalid = true
      log.warn("HSI_SECRETS_KEY is not 64 hex characters; notification secrets are unavailable")
    }
    return null
  }
  return Buffer.from(raw, "hex")
}

export function isEncrypted(value: string): boolean {
  return value.startsWith(PREFIX)
}

function requireKey(key: Buffer | null | undefined): Buffer {
  const k = key === undefined ? secretsKey() : key
  if (!k) throw new SecretsError("HSI_SECRETS_KEY missing")
  return k
}

export function encryptSecret(plain: string, key?: Buffer | null): string {
  const k = requireKey(key)
  const iv = randomBytes(12)
  const cipher = createCipheriv("aes-256-gcm", k, iv)
  const data = Buffer.concat([cipher.update(plain, "utf8"), cipher.final()])
  const tag = cipher.getAuthTag()
  return `${PREFIX}${iv.toString("base64")}:${tag.toString("base64")}:${data.toString("base64")}`
}

export function decryptSecret(value: string, key?: Buffer | null): string {
  const k = requireKey(key)
  try {
    const [iv, tag, data] = value.slice(PREFIX.length).split(":")
    const decipher = createDecipheriv("aes-256-gcm", k, Buffer.from(iv!, "base64"))
    decipher.setAuthTag(Buffer.from(tag!, "base64"))
    return Buffer.concat([decipher.update(Buffer.from(data!, "base64")), decipher.final()]).toString("utf8")
  } catch {
    throw new SecretsError(UNREADABLE_SECRETS)
  }
}

/** Plaintext passthrough for values stored before encryption existed. */
export function revealSecret(value: string, key?: Buffer | null): string {
  return isEncrypted(value) ? decryptSecret(value, key) : value
}
